swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: "1.0.0"
    termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            parameters:
                - in: body
                  name: body
                  description: Login Payload
                  required: true
                  schema:
                      $ref: "#/definitions/Login"
            produces:
                - application/json
            responses:
                "200":
                    description: Login Successfully
                    schema:
                        $ref: "#/definitions/LoginResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            parameters:
                - in: body
                  name: body
                  description: Signup Payload
                  required: true
                  schema:
                      $ref: "#/definitions/User"
            produces:
                - application/json
            responses:
                "200":
                    description: Signup Successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

    /user/profile:
        post:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: Fetch User Profile
            description: API for fetching a user profile
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: User profile retrieved successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: Update User Profile
            description: API for updating a user profile
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: "#/definitions/UserProfile"
            produces:
                - application/json
            responses:
                "200":
                    description: User profile updated successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

    # Nouveau : Création d'une transaction
    /user/{userId}/account/{accountId}/transactions/NewTransaction:
        post:
            tags:
                - Transactions
            summary: Create a New Transaction
            description: Allows a user to create a financial transaction on their account.
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: string
                  description: Unique identifier of the user.
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account.
                - in: body
                  name: body
                  required: true
                  schema:
                      $ref: "#/definitions/NewTransaction"
            produces:
                - application/json
            responses:
                "201":
                    description: Transaction created successfully
                    schema:
                        $ref: "#/definitions/Transaction"
                "400":
                    description: Invalid transaction data

    # Nouveau : Récupère les transactions d'un compte spécifique
    /user/{userId}/account/{accountId}/transactions:
        get:
            tags:
                - Transactions
            summary: Get Transactions for a Specific Account
            description: Retrieves a list of transactions for a specific account
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: string
                  description: Unique identifier of the user.
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account.
            produces:
                - application/json
            responses:
                "200":
                    description: List of transactions retrieved successfully
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/Transaction"
                "404":
                    description: Account not found

    # Nouveau : Récupère une transaction spécifique par son ID
    /user/{userId}/account/{accountId}/transactions/{transactionId}:
        get:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Get Transaction by ID
            description: Retrieves the details of a specific transaction using its unique identifier.
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: string
                  description: Unique identifier of the user.
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account.
                - in: path
                  name: transactionId
                  required: true
                  type: string
                  description: Unique identifier of the transaction to retrieve.
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction retrieved successfully
                    schema:
                        $ref: "#/definitions/Transaction"
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found

        # Nouveau : Supprimer une transaction
        delete:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Delete a Transaction
            description: API to delete a financial transaction.
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: string
                  description: Unique identifier of the user.
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account.
                - in: path
                  name: transactionId
                  required: true
                  type: string
                  description: Unique identifier of the transaction to delete.
            responses:
                "200":
                    description: Transaction deleted successfully.
                "401":
                    description: Unauthorized.
                "404":
                    description: Transaction not found

    # Nouveau: Mise à jour de la catégorie de la transaction
    /user/{userId}/account/{accountId}/transactions/{transactionId}/category:
        patch:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Update Transaction Category
            description: API to update the category of a financial transaction.
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: string
                  description: Unique identifier of the user.
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account.
                - in: path
                  name: transactionId
                  required: true
                  type: string
                  description: Unique identifier of the transaction to update.
                - in: body
                  name: body
                  required: true
                  schema:
                      $ref: "#/definitions/UpdateTransactionCategory"
            responses:
                "200":
                    description: Transaction category updated successfully.
                "400":
                    description: Invalid transaction category data.
                "401":
                    description: Unauthorized.
                "404":
                    description: Transaction not found

    # Nouveau : Mise à jour des notes de transaction
    /user/{userId}/account/{accountId}/transactions/{transactionId}/notes:
        patch:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Update Transaction Notes
            description: API to update the notes of a financial transaction.
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: string
                  description: Unique identifier of the user.
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account.
                - in: path
                  name: transactionId
                  required: true
                  type: string
                  description: Unique identifier of the transaction to update.
                - in: body
                  name: body
                  required: true
                  schema:
                      $ref: "#/definitions/UpdateTransactionNotes"
            responses:
                "200":
                    description: Transaction notes updated successfully.
                "400":
                    description: Invalid transaction notes data.
                "401":
                    description: Unauthorized.
                "404":
                    description: Transaction not found

securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header

definitions:
    User:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name

    Login:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password

    ApiResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                    email:
                        type: string

    LoginResponse:
        type: object
        properties:
            token:
                type: string

    UserProfile:
        type: object
        properties:
            firstName:
                type: string
            lastName:
                type: string

    NewTransaction:
        type: object
        properties:
            accountId:
                type: string
                description: Unique identifier of the account on which the transaction is performed.
            type:
                type: string
                enum: [deposit, debit, payment, transfer]
                description: Type of transaction (deposit, withdrawal, payment, transfer).
            amount:
                type: number
                description: Amount of the transaction.
            date:
                type: string
                format: date-time
                description: Date and time when the transaction was performed.
        required:
            - accountId
            - type
            - amount
            - date

    Transaction:
        type: object
        properties:
            id:
                type: string
                description: Unique identifier of the transaction.
            accountId:
                type: string
                description: Unique identifier of the account associated with the transaction.
            type:
                type: string
                enum: [deposit, debit, payment, transfer]
                description: Type of transaction performed.
            amount:
                type: number
                description: Amount of the transaction.
            date:
                type: string
                format: date-time
                description: Date and time of the transaction.

    UpdateTransactionCategory:
        type: object
        properties:
            category:
                type: string
                description: The new category for the transaction.
        required:
            - category

    UpdateTransactionNotes:
        type: object
        properties:
            notes:
                type: string
                description: The new notes for the transaction.
        required:
            - notes
